export type Page = 
  | 'home' 
  | 'predictor' 
  | 'chatbot' 
  | 'precautions' 
  | 'impact' 
  | 'settings'
  | 'login';

export type Language = 'en' | 'hi' | 'mr';

export const translations = {
  en: {
    welcome: "Welcome to PreventX",
    tagline: "AI Health Companion for Bharat",
    subtitle: "Early Prediction of Diabetes, Hypertension & Anemia",
    startPrediction: "Start Prediction",
    tryVoice: "Try Voice Demo",
    checkDiabetes: "Check my diabetes risk",
    symptoms: "Tell me my symptoms",
    checkBP: "Check my blood pressure",
    preventxDesc: "PreventX is India's first multilingual AI healthcare platform with voice input — designed for rural and urban India alike. Powered by ensemble ML models and Gemini AI, it provides personalized health insights in English, Hindi, and Marathi.",
    home: "Home",
    predictor: "Disease Predictor",
    chatbot: "Health AI Chat",
    precautions: "Precautions",
    impact: "Impact Simulator",
    settings: "Settings",
    logout: "Logout",
    checkHealthRisk: "Check My Health Risk",
    signUp: "Sign Up",
    diseasePredictionModels: "Disease Prediction Models",
    modelsDesc: "Detailed information about the machine learning models used for disease prediction, including input parameters, their descriptions, and expected formats.",
    understandingInputs: "Understanding the Inputs",
    commonInputTypes: "Common Input Types",
    binaryType: "Binary (0/1): 0 typically means 'No' and 1 means 'Yes'",
    categoricalType: "Categorical: Numbers representing different categories (see description for mapping)",
    numericalType: "Numerical: Actual measurements with units specified",
    imagesType: "Images: For conditions like pneumonia, upload a clear X-ray image",
    parameter: "Parameter",
    type: "Type",
    description: "Description",
    alzheimer: "Alzheimer",
    heartDiseaseTitle: "Heart Disease",
    accuracyLabel: "Accuracy",
    inputParameters: "Input Parameters",
    randomForest: "Random Forest",
    ensembleModel: "Ensemble (RF + XGB + LGBM)",
    ageDesc: "Age of the patient",
    genderDesc: "Biological sex",
    eduDesc: "Years of education",
    mmseDesc: "Mini-Mental State Examination score (0-30)",
    etivDesc: "Estimated Total Intracranial Volume",
    nwbvDesc: "Normalized Whole Brain Volume",
    hemoDesc: "Hemoglobin level in blood",
    mchDesc: "Mean Corpuscular Hemoglobin",
    mchcDesc: "Mean Corpuscular Hemoglobin Concentration",
    mcvDesc: "Mean Corpuscular Volume",
    pregDesc: "Number of pregnancies",
    glucDesc: "Plasma glucose concentration",
    bpDesc: "Diastolic blood pressure",
    skinDesc: "Triceps skin fold thickness",
    insDesc: "2-Hour serum insulin",
    bmiDesc: "Body mass index",
    dpfDesc: "Diabetes pedigree function",
    cpDesc: "Chest pain type (0-3)",
    trestbpsDesc: "Resting blood pressure",
    cholDesc: "Serum cholesterol",
    fbsDesc: "Fasting blood sugar > 120 mg/dL",
    restecgDesc: "Resting electrocardiographic results",
    thalachDesc: "Maximum heart rate achieved",
    exangDesc: "Exercise induced angina",
    livesImpacted: "14L+ Lives Impacted",
    diseasesCovered: "3 Diseases Covered",
    accuracy: "93%+ Accuracy",
    ruralReach: "85% Rural Reach",
    selectDisease: "Check your risk for these conditions",
    predictorDesc: "Our advanced AI models analyze your health data to predict risks for Diabetes, Hypertension, and Anemia with 93%+ accuracy.",
    diabetes: "Diabetes",
    hypertension: "Hypertension",
    anemia: "Anemia",
    startAssessment: "Start New Assessment",
    trySaying: "Try saying:",
    bodyVisualization: "Body Visualization",
    healthOverview: "Health Overview",
    realTimeVitals: "Real-time Vitals",
    voiceInteraction: "Voice Interaction",
    navigationMenu: "Navigation Menu",
    quickGuide: "Quick Guide",
    getStarted: "Get Started",
    next: "Next",
    back: "Back",
    healthPrecautions: "Health Precautions",
    precautionsSubtitle: "Follow these recommended tips from experts.",
    diabetesPrevention: "Diabetes Prevention",
    hypertensionPrevention: "Hypertension Prevention",
    anemiaPrevention: "Anemia Prevention",
    needPlan: "Need a personalized plan?",
    nutriPlanDesc: "Talk to our AI Nutrition Assistant to get a diet plan specifically designed for your health condition and local food availability.",
    talkNutriBot: "Talk to NutriBot",
    precautionsNote: "Note: These are general precautions. Always consult with a healthcare professional for personalized medical advice.",
    impactSimulator: "Impact Simulator",
    impactSubtitle: "Visualize the potential health impact of PreventX on your community.",
    populationSettings: "Population Settings",
    people: "People",
    smallVillage: "Small Village",
    largeTown: "Large Town",
    diabetesDetected: "Diabetes Detected",
    hypertensionRisks: "Hypertension Risks",
    anemiaIdentified: "Anemia Identified",
    earlyDetectionImpact: "Early Detection Impact",
    inAVillageOf: "In a village of",
    detectedEarly: "detected early, preventing long-term complications.",
    preventedEarly: "prevented through early lifestyle intervention.",
    identifiedImproving: "identified, improving maternal and child health.",
    distribution: "Distribution",
    calculateImpact: "Calculate Impact",
    city: "City",
    allIndia: "All India",
    casesPreventable: "cases preventable per year with early AI screening in a population of",
    estSavings: "Est. ₹{amount} L healthcare costs saved annually",
    atRiskPopulation: "At-risk population",
    likelyUndiagnosed: "Likely undiagnosed",
    detectableByAI: "Detectable by AI",
    preventableCases: "Preventable cases",
    methodology: "Methodology",
    diabetesPrevalence: "Diabetes prevalence: 11.7% (ICMR-INDIAB Study)",
    hypertensionPrevalence: "Hypertension prevalence: 28.6% (India Hypertension Control Initiative)",
    anemiaPrevalence: "Anemia prevalence: 53% (NFHS-5, women 15-49)",
    undiagnosedRate: "Undiagnosed rate: ~50% (WHO India Report 2023)",
    earlyDetectionAI: "Early detection via AI screening: 35-45% of undiagnosed cases",
    preventionRate: "Prevention rate: 60% with lifestyle intervention (DPP Study)",
    shareWithDoctor: "Share with Doctor",
    shareWithDoctorDesc: "Generate a QR code and secure link to share your latest prediction report with a healthcare professional.",
    generateShareLink: "Generate QR Code & Share Link",
    nutriSubtitle: "Personalized diet plans for Bharat",
    nutriPlaceholder: "Ask about diet, food, or nutrition...",
    symptomsSubtitle: "AI-powered symptom analysis",
    symptomsPlaceholder: "Please describe your symptoms and I'll try to help. You can also use voice input",
    suggestDietAnemia: "Suggest diet for anemia",
    lowSugarPlan: "Low sugar Indian meal plan",
    threeDayPlan: "3-day healthy diet plan",
    feelDizzy: "I feel dizzy",
    chestHurts: "My chest hurts",
    persistentCough: "I have a persistent cough",
    anemiaPrediction: "Anemia Prediction",
    diabetesPrediction: "Diabetes Prediction",
    hypertensionPrediction: "Hypertension Prediction",
    tabularInput: "Tabular Input",
    imageAnalysis: "Image Analysis",
    uploadLabReport: "Upload a photo of your lab report / blood test.",
    uploadLabReportDesc: "Upload a photo of your lab report / blood test.",
    clickOrDragLabReport: "Click or drag & drop a lab report image here",
    supportsJpgPng: "Supports JPG, PNG (max 5MB)",
    loadSampleReport: "Load Sample Report",
    multiModalAnalysis: "Multi-Modal: Palm / Conjunctiva Image Analysis",
    multiModalDesc: "Upload a clear photo of your palm, nail bed, or inner lower eyelid for AI-powered color analysis. The system extracts RGB channel percentages and estimates hemoglobin levels.",
    selectGender: "Select Gender",
    clickOrDragPalm: "Click or drag & drop a palm photo here",
    loadSamplePalm: "Load Sample Palm",
    analyseImage: "Analyse Image",
    quickFill: "Quick fill option (select a random sample from database)",
    predict: "Predict",
    processingReport: "Processing report...",
    age: "Age",
    sex: "Sex",
    male: "Male",
    female: "Female",
    glucose: "Glucose",
    bloodPressure: "Blood Pressure",
    bmi: "BMI",
    insulin: "Insulin",
    pregnancies: "Pregnancies",
    skinThickness: "Skin Thickness",
    diabetesPedigree: "Diabetes Pedigree Function",
    smoking: "Smoking",
    alcohol: "Alcohol Intent",
    activity: "Physical Activity",
    salt: "Salt Intake",
    chronic: "Chronic Conditions",
    familyHistory: "Family History",
    heartDisease: "Previous Heart Disease",
    medication: "Medication Use",
    stress: "Stress Level",
    sleep: "Sleep Hours",
    systolic: "Systolic BP",
    diastolic: "Diastolic BP",
    heartRate: "Heart Rate",
    cholesterol: "Cholesterol",
    creatinine: "Creatinine",
    dietType: "Diet Type",
    modelInsightsDashboard: "Model Insights Dashboard",
    modelInsightsDesc: "Performance metrics, SHAP explainability, and risk trend analysis for all ensemble models.",
    liveAnalysis: "Live Analysis",
    accuracyComparison: "Model Accuracy Comparison",
    model: "Model",
    topFeatures: "Top Features",
    riskTrendProjection: "6-Month Risk Trend Projection",
    riskTrendDesc: "Simulated risk reduction with proper treatment adherence and lifestyle changes.",
    ensembleArchitecture: "Ensemble Architecture",
    architecture: "Architecture",
    features: "Features",
    trainingSamples: "Training Samples",
    finalAccuracy: "Final Accuracy",
    projectedTrendsNote: "Projected trends for educational purposes only.",
    softVotingNote: "All models use Soft Voting Ensemble (RandomForest + XGBoost + LightGBM)",
    keyFeatures: "Key Features",
    diseasePredictionTitle: "Disease Prediction",
    diseasePredictionDesc: "Ensemble ML (RF + XGBoost + LightGBM) for Diabetes, Anemia, Hypertension",
    voiceInputTitle: "Voice Input",
    voiceInputDesc: "Speak your symptoms or health data — works in English, Hindi & Marathi",
    multiModalAnemiaTitle: "Multi-Modal Anemia",
    multiModalAnemiaDesc: "Upload palm photo for AI-powered color analysis + tabular ensemble fusion",
    shapExplainabilityTitle: "SHAP Explainability",
    shapExplainabilityDesc: "See exactly why each prediction was made with visual SHAP bars",
    personalizedPlansTitle: "Personalized Plans",
    personalizedPlansDesc: "Gemini AI generates diet, exercise, and lifestyle plans in your language",
    pdfReportsTitle: "PDF Reports",
    pdfReportsDesc: "Download professional clinical reports with one click",
    pancreasMonitoring: "Pancreas: Monitoring Diabetes Risk",
    heartMonitoring: "Heart: Monitoring Hypertension",
    bloodMonitoring: "Blood: Monitoring Anemia",
    demoMode: "Demo Mode – Auto-fill Indian Patient Data & Predict",
    futureRiskTimeline: "Future Risk Timeline",
    shapExplainabilityPlots: "SHAP Explainability Plots",
    shapDesc: "Beeswarm plots show how each feature impacts individual predictions. Red = high feature value, Blue = low.",
    shapFeatureImpact: "SHAP Feature Impact",
    shapValueImpact: "SHAP value (impact on model output)",
    shapMeanImportance: "SHAP Mean Importance",
    meanFeatureImportance: "Mean Feature Importance",
    meanShapValueImpact: "mean(|SHAP value|) (average impact on model output magnitude)",
    bpProduct: "BP Product",
    bmiAge: "BMI Age",
    stressLevel: "Stress Level",
    riskCombo: "Risk Combo",
    cholGlucose: "Chol Glucose",
    hb: "Hb",
    greenPixel: "%Green pixel",
    redPixel: "%Red Pixel",
    bluePixel: "%Blue pixel",
    featureValue: "Feature value",
    high: "High",
    low: "Low",
  },
  hi: {
    welcome: "PreventX में आपका स्वागत है",
    tagline: "भारत के लिए AI स्वास्थ्य साथी",
    subtitle: "मधुमेह, उच्च रक्तचाप और एनीमिया की प्रारंभिक भविष्यवाणी",
    startPrediction: "भविष्यवाणी शुरू करें",
    tryVoice: "वॉयस डेमो आज़माएं",
    checkDiabetes: "मेरा मधुमेह जोखिम जांचें",
    symptoms: "मेरे लक्षण बताओ",
    checkBP: "मेरा रक्तचाप जांचें",
    preventxDesc: "PreventX भारत का पहला बहुभाषी AI स्वास्थ्य सेवा मंच है जिसमें वॉयस इनपुट है - जो ग्रामीण और शहरी भारत के लिए समान रूप से डिज़ाइन किया गया है। एंसेम्बल ML मॉडल और जेमिनी AI द्वारा संचालित, यह अंग्रेजी, हिंदी और मराठी में व्यक्तिगत स्वास्थ्य अंतर्दृष्टि प्रदान करता है।",
    home: "होम",
    predictor: "रोग भविष्यवक्ता",
    chatbot: "स्वास्थ्य AI चैट",
    precautions: "सावधानियां",
    impact: "प्रभाव सिम्युलेटर",
    settings: "सेटिंग्स",
    logout: "लॉगआउट",
    checkHealthRisk: "मेरा स्वास्थ्य जोखिम जांचें",
    signUp: "साइन अप करें",
    diseasePredictionModels: "रोग भविष्यवाणी मॉडल",
    modelsDesc: "रोग भविष्यवाणी के लिए उपयोग किए जाने वाले मशीन लर्निंग मॉडल के बारे में विस्तृत जानकारी, जिसमें इनपुट पैरामीटर, उनके विवरण और अपेक्षित प्रारूप शामिल हैं।",
    understandingInputs: "इनपुट को समझना",
    commonInputTypes: "सामान्य इनपुट प्रकार",
    binaryType: "बाइनरी (0/1): 0 का अर्थ आमतौर पर 'नहीं' और 1 का अर्थ 'हाँ' होता है",
    categoricalType: "श्रेणीबद्ध: विभिन्न श्रेणियों का प्रतिनिधित्व करने वाली संख्याएं (मैपिंग के लिए विवरण देखें)",
    numericalType: "संख्यात्मक: निर्दिष्ट इकाइयों के साथ वास्तविक माप",
    imagesType: "छवियां: निमोनिया जैसी स्थितियों के लिए, एक स्पष्ट एक्स-रे छवि अपलोड करें",
    parameter: "पैरामीटर",
    type: "प्रकार",
    description: "विवरण",
    alzheimer: "अल्जाइमर",
    heartDiseaseTitle: "हृदय रोग",
    accuracyLabel: "सटीकता",
    inputParameters: "इनपुट पैरामीटर",
    randomForest: "रैंडम फॉरेस्ट",
    ensembleModel: "एंसेम्बल (RF + XGB + LGBM)",
    ageDesc: "रोगी की आयु",
    genderDesc: "जैविक लिंग",
    eduDesc: "शिक्षा के वर्ष",
    mmseDesc: "मिनी-मेंटल स्टेट एग्जामिनेशन स्कोर (0-30)",
    etivDesc: "अनुमानित कुल इंट्राक्रानियल वॉल्यूम",
    nwbvDesc: "सामान्यीकृत संपूर्ण मस्तिष्क आयतन",
    hemoDesc: "रक्त में हीमोग्लोबिन का स्तर",
    mchDesc: "मीन कॉर्पस्कुलर हीमोग्लोबिन",
    mchcDesc: "मीन कॉर्पस्कुलर हीमोग्लोबिन सांद्रता",
    mcvDesc: "मीन कॉर्पस्कुलर वॉल्यूम",
    pregDesc: "गर्भावस्था की संख्या",
    glucDesc: "प्लाज्मा ग्लूकोज सांद्रता",
    bpDesc: "डायस्टोलिक रक्तचाप",
    skinDesc: "ट्राइसेप्स स्किन फोल्ड मोटाई",
    insDesc: "2-घंटे सीरम इंसुलिन",
    bmiDesc: "बॉडी मास इंडेक्स",
    dpfDesc: "मधुमेह वंशावली कार्य",
    cpDesc: "सीने में दर्द का प्रकार (0-3)",
    trestbpsDesc: "विश्राम रक्तचाप",
    cholDesc: "सीरम कोलेस्ट्रॉल",
    fbsDesc: "फास्टिंग ब्लड शुगर > 120 mg/dL",
    restecgDesc: "विश्राम इलेक्ट्रोकार्डियोग्राफिक परिणाम",
    thalachDesc: "अधिकतम हृदय गति प्राप्त की",
    exangDesc: "व्यायाम प्रेरित एनजाइना",
    livesImpacted: "14L+ जीवन प्रभावित",
    diseasesCovered: "3 बीमारियां कवर",
    accuracy: "93%+ सटीकता",
    ruralReach: "85% ग्रामीण पहुंच",
    selectDisease: "इन स्थितियों के लिए अपने जोखिम की जांच करें",
    predictorDesc: "हमारे उन्नत AI मॉडल 93%+ सटीकता के साथ मधुमेह, उच्च रक्तचाप और एनीमिया के जोखिमों की भविष्यवाणी करने के लिए आपके स्वास्थ्य डेटा का विश्लेषण करते हैं।",
    diabetes: "मधुमेह",
    hypertension: "उच्च रक्तचाप",
    anemia: "एनीमिया",
    startAssessment: "नया मूल्यांकन शुरू करें",
    trySaying: "कहने की कोशिश करें:",
    bodyVisualization: "शरीर विज़ुअलाइज़ेशन",
    healthOverview: "स्वास्थ्य अवलोकन",
    realTimeVitals: "रीयल-टाइम विटल्स",
    voiceInteraction: "वॉयस इंटरेक्शन",
    navigationMenu: "नेविगेशन मेनू",
    quickGuide: "त्वरित मार्गदर्शिका",
    getStarted: "शुरू करें",
    next: "अगला",
    back: "पीछे",
    healthPrecautions: "स्वास्थ्य सावधानियां",
    precautionsSubtitle: "विशेषज्ञों के इन अनुशंसित सुझावों का पालन करें।",
    diabetesPrevention: "मधुमेह की रोकथाम",
    hypertensionPrevention: "उच्च रक्तचाप की रोकथाम",
    anemiaPrevention: "एनीमिया की रोकथाम",
    needPlan: "एक व्यक्तिगत योजना की आवश्यकता है?",
    nutriPlanDesc: "अपनी स्वास्थ्य स्थिति और स्थानीय भोजन की उपलब्धता के लिए विशेष रूप से डिज़ाइन की गई आहार योजना प्राप्त करने के लिए हमारे AI पोषण सहायक से बात करें।",
    talkNutriBot: "न्यूट्रीबॉट से बात करें",
    precautionsNote: "नोट: ये सामान्य सावधानियां हैं। व्यक्तिगत चिकित्सा सलाह के लिए हमेशा एक स्वास्थ्य देखभाल पेशेवर से परामर्श लें।",
    impactSimulator: "प्रभाव सिम्युलेटर",
    impactSubtitle: "अपने समुदाय पर PreventX के संभावित स्वास्थ्य प्रभाव की कल्पना करें।",
    populationSettings: "जनसंख्या सेटिंग्स",
    people: "लोग",
    smallVillage: "छोटा गाँव",
    largeTown: "बड़ा शहर",
    diabetesDetected: "मधुमेह का पता चला",
    hypertensionRisks: "उच्च रक्तचाप जोखिम",
    anemiaIdentified: "एनीमिया की पहचान",
    earlyDetectionImpact: "प्रारंभिक पहचान प्रभाव",
    inAVillageOf: "एक गाँव में",
    detectedEarly: "जल्दी पता चला, दीर्घकालिक जटिलताओं को रोकना।",
    preventedEarly: "प्रारंभिक जीवनशैली हस्तक्षेप के माध्यम से रोका गया।",
    identifiedImproving: "पहचान की गई, मातृ और शिशु स्वास्थ्य में सुधार।",
    distribution: "वितरण",
    calculateImpact: "प्रभाव की गणना करें",
    city: "शहर",
    allIndia: "अखिल भारतीय",
    casesPreventable: "प्रति वर्ष रोके जाने योग्य मामले, प्रारंभिक AI स्क्रीनिंग के साथ",
    estSavings: "अनुमानित ₹{amount} L स्वास्थ्य देखभाल लागत प्रति वर्ष बचाई गई",
    atRiskPopulation: "जोखिम वाली जनसंख्या",
    likelyUndiagnosed: "संभावित रूप से अनिदानित",
    detectableByAI: "AI द्वारा पता लगाने योग्य",
    preventableCases: "रोके जाने योग्य मामले",
    methodology: "कार्यप्रणाली",
    diabetesPrevalence: "मधुमेह प्रसार: 11.7% (ICMR-INDIAB अध्ययन)",
    hypertensionPrevalence: "उच्च रक्तचाप प्रसार: 28.6% (भारत उच्च रक्तचाप नियंत्रण पहल)",
    anemiaPrevalence: "एनीमिया प्रसार: 53% (NFHS-5, महिलाएं 15-49)",
    undiagnosedRate: "अनिदानित दर: ~50% (WHO भारत रिपोर्ट 2023)",
    earlyDetectionAI: "AI स्क्रीनिंग के माध्यम से प्रारंभिक पहचान: अनिदानित मामलों का 35-45%",
    preventionRate: "रोकथाम दर: जीवनशैली हस्तक्षेप के साथ 60% (DPP अध्ययन)",
    shareWithDoctor: "डॉक्टर के साथ साझा करें",
    shareWithDoctorDesc: "एक स्वास्थ्य देखभाल पेशेवर के साथ अपनी नवीनतम भविष्यवाणी रिपोर्ट साझा करने के लिए एक QR कोड और सुरक्षित लिंक उत्पन्न करें।",
    generateShareLink: "QR कोड और साझा लिंक उत्पन्न करें",
    nutriSubtitle: "भारत के लिए व्यक्तिगत आहार योजना",
    nutriPlaceholder: "आहार, भोजन या पोषण के बारे में पूछें...",
    symptomsSubtitle: "AI-संचालित लक्षण विश्लेषण",
    symptomsPlaceholder: "कृपया अपने लक्षणों का वर्णन करें और मैं मदद करने की कोशिश करूँगा। आप वॉयस इनपुट का भी उपयोग कर सकते हैं",
    suggestDietAnemia: "एनीमिया के लिए आहार का सुझाव दें",
    lowSugarPlan: "कम चीनी वाली भारतीय भोजन योजना",
    threeDayPlan: "3-दिवसीय स्वस्थ आहार योजना",
    feelDizzy: "मुझे चक्कर आ रहे हैं",
    chestHurts: "मेरे सीने में दर्द है",
    persistentCough: "मुझे लगातार खांसी है",
    anemiaPrediction: "एनीमिया की भविष्यवाणी",
    diabetesPrediction: "मधुमेह की भविष्यवाणी",
    hypertensionPrediction: "उच्च रक्तचाप की भविष्यवाणी",
    tabularInput: "टैबुलर इनपुट",
    imageAnalysis: "छवि विश्लेषण",
    uploadLabReport: "अपनी लैब रिपोर्ट / रक्त परीक्षण की एक फोटो अपलोड करें।",
    uploadLabReportDesc: "अपनी लैब रिपोर्ट / रक्त परीक्षण की एक फोटो अपलोड करें।",
    clickOrDragLabReport: "लैब रिपोर्ट की छवि को यहां क्लिक करें या खींचें और छोड़ें",
    supportsJpgPng: "JPG, PNG का समर्थन करता है (अधिकतम 5MB)",
    loadSampleReport: "नमूना रिपोर्ट लोड करें",
    multiModalAnalysis: "मल्टी-मोडल: हथेली / कंजंक्टिवा छवि विश्लेषण",
    multiModalDesc: "AI-संचालित रंग विश्लेषण के लिए अपनी हथेली, नाखून या निचली पलक की एक स्पष्ट फोटो अपलोड करें। सिस्टम RGB चैनल प्रतिशत निकालता है और हीमोग्लोबिन स्तर का अनुमान लगाता है।",
    selectGender: "लिंग चुनें",
    clickOrDragPalm: "हथेली की फोटो को यहां क्लिक करें या खींचें और छोड़ें",
    loadSamplePalm: "नमूना हथेली लोड करें",
    analyseImage: "छवि का विश्लेषण करें",
    quickFill: "त्वरित भरने का विकल्प (डेटाबेस से एक यादृच्छिक नमूना चुनें)",
    predict: "भविष्यवाणी करें",
    processingReport: "रिपोर्ट संसाधित की जा रही है...",
    age: "आयु",
    sex: "लिंग",
    male: "पुरुष",
    female: "महिला",
    glucose: "ग्लूकोज",
    bloodPressure: "रक्तचाप",
    bmi: "बीएमआई",
    insulin: "इंसुलिन",
    pregnancies: "गर्भावस्था",
    skinThickness: "त्वचा की मोटाई",
    diabetesPedigree: "मधुमेह वंशावली कार्य",
    smoking: "धूम्रपान",
    alcohol: "शराब का इरादा",
    activity: "शारीरिक गतिविधि",
    salt: "नमक का सेवन",
    chronic: "पुरानी स्थितियां",
    familyHistory: "पारिवारिक इतिहास",
    heartDisease: "पिछला हृदय रोग",
    medication: "दवा का उपयोग",
    stress: "तनाव का स्तर",
    sleep: "नींद के घंटे",
    systolic: "सिस्टोलिक बीपी",
    diastolic: "डायस्टोलिक बीपी",
    heartRate: "हृदय गति",
    cholesterol: "कोलेस्ट्रॉल",
    creatinine: "क्रिएटिनिन",
    dietType: "आहार का प्रकार",
    modelInsightsDashboard: "मॉडल अंतर्दृष्टि डैशबोर्ड",
    modelInsightsDesc: "सभी एंसेम्बल मॉडल के लिए प्रदर्शन मेट्रिक्स, SHAP व्याख्यात्मकता और जोखिम प्रवृत्ति विश्लेषण।",
    liveAnalysis: "लाइव विश्लेषण",
    accuracyComparison: "मॉडल सटीकता तुलना",
    model: "मॉडल",
    topFeatures: "शीर्ष विशेषताएं",
    riskTrendProjection: "6-महीने का जोखिम प्रवृत्ति प्रक्षेपण",
    riskTrendDesc: "उचित उपचार पालन और जीवनशैली में बदलाव के साथ सिम्युलेटेड जोखिम में कमी।",
    ensembleArchitecture: "एंसेम्बल आर्किटेक्चर",
    architecture: "आर्किटेक्चर",
    features: "विशेषताएं",
    trainingSamples: "प्रशिक्षण नमूने",
    finalAccuracy: "अंतिम सटीकता",
    projectedTrendsNote: "केवल शैक्षिक उद्देश्यों के लिए अनुमानित रुझान।",
    softVotingNote: "सभी मॉडल सॉफ्ट वोटिंग एंसेम्बल (RandomForest + XGBoost + LightGBM) का उपयोग करते हैं",
    keyFeatures: "प्रमुख विशेषताएं",
    diseasePredictionTitle: "रोग भविष्यवाणी",
    diseasePredictionDesc: "मधुमेह, एनीमिया, उच्च रक्तचाप के लिए एंसेम्बल ML (RF + XGBoost + LightGBM)",
    voiceInputTitle: "वॉयस इनपुट",
    voiceInputDesc: "अपने लक्षण या स्वास्थ्य डेटा बोलें - अंग्रेजी, हिंदी और मराठी में काम करता है",
    multiModalAnemiaTitle: "मल्टी-मोडल एनीमिया",
    multiModalAnemiaDesc: "AI-संचालित रंग विश्लेषण + टैबुलर एंसेम्बल फ्यूजन के लिए हथेली का फोटो अपलोड करें",
    shapExplainabilityTitle: "SHAP व्याख्यात्मकता",
    shapExplainabilityDesc: "विजुअल SHAP बार के साथ ठीक से देखें कि प्रत्येक भविष्यवाणी क्यों की गई थी",
    personalizedPlansTitle: "व्यक्तिगत योजनाएं",
    personalizedPlansDesc: "Gemini AI आपकी भाषा में आहार, व्यायाम और जीवनशैली योजनाएं बनाता है",
    pdfReportsTitle: "PDF रिपोर्ट",
    pdfReportsDesc: "एक क्लिक के साथ पेशेवर नैदानिक रिपोर्ट डाउनलोड करें",
    pancreasMonitoring: "अग्न्याशय: मधुमेह जोखिम की निगरानी",
    heartMonitoring: "हृदय: उच्च रक्तचाप की निगरानी",
    bloodMonitoring: "रक्त: एनीमिया की निगरानी",
    demoMode: "डेमो मोड - भारतीय रोगी डेटा ऑटो-फिल करें और भविष्यवाणी करें",
    futureRiskTimeline: "भविष्य का जोखिम टाइमलाइन",
    shapExplainabilityPlots: "SHAP व्याख्यात्मकता प्लॉट",
    shapDesc: "बीस्वर्म प्लॉट दिखाते हैं कि प्रत्येक विशेषता व्यक्तिगत भविष्यवाणियों को कैसे प्रभावित करती है। लाल = उच्च विशेषता मान, नीला = निम्न।",
    shapFeatureImpact: "SHAP विशेषता प्रभाव",
    shapValueImpact: "SHAP मान (मॉडल आउटपुट पर प्रभाव)",
    shapMeanImportance: "SHAP माध्य महत्व",
    meanFeatureImportance: "माध्य विशेषता महत्व",
    meanShapValueImpact: "माध्य (|SHAP मान|) (मॉडल आउटपुट परिमाण पर औसत प्रभाव)",
    bpProduct: "बीपी उत्पाद",
    bmiAge: "बीएमआई आयु",
    stressLevel: "तनाव का स्तर",
    riskCombo: "जोखिम कॉम्बो",
    cholGlucose: "चोल ग्लूकोज",
    hb: "एचबी",
    greenPixel: "%हरा पिक्सेल",
    redPixel: "%लाल पिक्सेल",
    bluePixel: "%नीला पिक्सेल",
    featureValue: "विशेषता मान",
    high: "उच्च",
    low: "निम्न",
  },
  mr: {
    welcome: "PreventX मध्ये आपले स्वागत आहे",
    tagline: "भारतासाठी AI आरोग्य सोबती",
    subtitle: "मधुमेह, उच्च रक्तचाप आणि ॲनिमियाचे लवकर भाकीत",
    startPrediction: "भविष्यवाणी सुरू करा",
    tryVoice: "व्हॉइस डेमो वापरून पहा",
    checkDiabetes: "माझा मधुमेह धोका तपासा",
    symptoms: "माझी लक्षणे सांगा",
    checkBP: "माझा रक्तदाब तपासा",
    preventxDesc: "PreventX हे व्हॉइस इनपुटसह भारतातील पहिले बहुभाषिक AI आरोग्य सेवा प्लॅटफॉर्म आहे - जे ग्रामीण आणि शहरी भारतासाठी समान रीतीने डिझाइन केलेले आहे। एन्सेम्बल ML मॉडेल्स आणि जेमिनी AI द्वारे समर्थित, ते इंग्रजी, हिंदी आणि मराठीमध्ये वैयक्तिक आरोग्य अंतर्दृष्टी प्रदान करते।",
    home: "होम",
    predictor: "रोग भविष्यवक्ता",
    chatbot: "आरोग्य AI चॅट",
    precautions: "सावधानता",
    impact: "प्रभाव सिम्युलेटर",
    settings: "सेटिंग्ज",
    logout: "लॉगआउट",
    checkHealthRisk: "माझा आरोग्य धोका तपासा",
    signUp: "साइन अप करा",
    diseasePredictionModels: "रोग भविष्यवाणी मॉडेल्स",
    modelsDesc: "रोग भविष्यवाणीसाठी वापरल्या जाणाऱ्या मशीन लर्निंग मॉडेल्सबद्दल तपशीलवार माहिती, ज्यामध्ये इनपुट पॅरामीटर्स, त्यांचे वर्णन आणि अपेक्षित स्वरूप समाविष्ट आहे।",
    understandingInputs: "इनपुट समजून घेणे",
    commonInputTypes: "सामान्य इनपुट प्रकार",
    binaryType: "बायनरी (0/1): 0 म्हणजे सामान्यतः 'नाही' आणि 1 म्हणजे 'हो' असा होतो",
    categoricalType: "कॅटेगोरिकल: विविध श्रेणींचे प्रतिनिधित्व करणारे क्रमांक (मॅपिंगसाठी वर्णन पहा)",
    numericalType: "न्यूमेरिकल: निर्दिष्ट युनिट्ससह वास्तविक मोजमाप",
    imagesType: "प्रतिमा: न्यूमोनियासारख्या परिस्थितींसाठी, स्पष्ट एक्स-रे प्रतिमा अपलोड करा",
    parameter: "पॅरामीटर",
    type: "प्रकार",
    description: "वर्णन",
    alzheimer: "अल्झायमर",
    heartDiseaseTitle: "हृदयविकार",
    accuracyLabel: "अचूकता",
    inputParameters: "इनपुट पॅरामीटर्स",
    randomForest: "रँडम फॉरेस्ट",
    ensembleModel: "एन्सेम्बल (RF + XGB + LGBM)",
    ageDesc: "रुग्णाचे वय",
    genderDesc: "जैविक लिंग",
    eduDesc: "शिक्षणाची वर्षे",
    mmseDesc: "मिनी-मेंटल स्टेट एक्झामिनेशन स्कोअर (0-30)",
    etivDesc: "अंदाजित एकूण इंट्राक्रॅनियल व्हॉल्यूम",
    nwbvDesc: "सामान्यीकृत संपूर्ण मेंदूचे प्रमाण",
    hemoDesc: "रक्तातील हिमोग्लोबिनची पातळी",
    mchDesc: "मीन कॉर्पस्कुलर हिमोग्लोबिन",
    mchcDesc: "मीन कॉर्पस्कुलर हिमोग्लोबिन एकाग्रता",
    mcvDesc: "मीन कॉर्पस्कुलर व्हॉल्यूम",
    pregDesc: "गर्भधारणेची संख्या",
    glucDesc: "प्लाझ्मा ग्लुकोज एकाग्रता",
    bpDesc: "डायस्टोलिक रक्तदाब",
    skinDesc: "ट्रायसेप्स स्किन फोल्ड जाडी",
    insDesc: "2-तास सीरम इन्सुलिन",
    bmiDesc: "बॉडी मास इंडेक्स",
    dpfDesc: "मधुमेह वंशावली कार्य",
    cpDesc: "छातीत दुखण्याचा प्रकार (0-3)",
    trestbpsDesc: "विश्रांतीचा रक्तदाब",
    cholDesc: "सीरम कोलेस्ट्रॉल",
    fbsDesc: "फास्टिंग ब्लड शुगर > 120 mg/dL",
    restecgDesc: "विश्रांतीचे इलेक्ट्रोकार्डियोग्राफिक परिणाम",
    thalachDesc: "जास्तीत जास्त हृदय गती गाठली",
    exangDesc: "व्यायाम प्रेरित एनजाइना",
    livesImpacted: "14L+ जीवन प्रभावित",
    diseasesCovered: "3 रोग कव्वर",
    accuracy: "93%+ अचूकता",
    ruralReach: "85% ग्रामीण पोहोच",
    selectDisease: "या परिस्थितींसाठी तुमची जोखीम तपासा",
    predictorDesc: "आमचे प्रगत AI मॉडेल 93%+ अचूकतेसह मधुमेह, उच्च रक्तचाप आणि ॲनिमियाच्या जोखमींचे भाकीत करण्यासाठी तुमच्या आरोग्य डेटाचे विश्लेषण करतात।",
    diabetes: "मधुमेह",
    hypertension: "उच्च रक्तचाप",
    anemia: "ॲनिमिया",
    startAssessment: "नवीन मूल्यांकन सुरू करा",
    trySaying: "म्हणून पहा:",
    bodyVisualization: "शरीर व्हिज्युअलायझेशन",
    healthOverview: "आरोग्य विहंगावलोकन",
    realTimeVitals: "रिअल-टाइम विटल्स",
    voiceInteraction: "व्हॉइस संवाद",
    navigationMenu: "नेव्हिगेशन मेनू",
    quickGuide: "त्वरित मार्गदर्शक",
    getStarted: "सुरू करा",
    next: "पुढील",
    back: "मागे",
    healthPrecautions: "आरोग्य खबरदारी",
    precautionsSubtitle: "तज्ञांच्या या शिफारस केलेल्या टिप्स फॉलो करा।",
    diabetesPrevention: "मधुमेह प्रतिबंध",
    hypertensionPrevention: "उच्च रक्तचाप प्रतिबंध",
    anemiaPrevention: "ॲनिमिया प्रतिबंध",
    needPlan: "वैयक्तिकृत योजनेची आवश्यकता आहे?",
    nutriPlanDesc: "तुमच्या आरोग्याची स्थिती आणि स्थानिक अन्नाच्या उपलब्धतेसाठी खास डिझाइन केलेले आहार नियोजन मिळवण्यासाठी आमच्या AI पोषण सहाय्यकाशी बोला।",
    talkNutriBot: "न्यूट्रीबॉटशी बोला",
    precautionsNote: "टीप: या सामान्य खबरदारी आहेत। वैयक्तिक वैद्यकीय सल्ल्यासाठी नेहमी आरोग्य सेवा व्यावसायिकाचा सल्ला घ्या।",
    impactSimulator: "प्रभाव सिम्युलेटर",
    impactSubtitle: "तुमच्या समुदायावर PreventX च्या संभाव्य आरोग्य प्रभावाची कल्पना करा।",
    populationSettings: "लोकसंख्या सेटिंग्ज",
    people: "लोक",
    smallVillage: "लहान गाव",
    largeTown: "मोठे शहर",
    diabetesDetected: "मधुमेह आढळला",
    hypertensionRisks: "उच्च रक्तचाप जोखीम",
    anemiaIdentified: "ॲनिमिया ओळखला",
    earlyDetectionImpact: "लवकर ओळख प्रभाव",
    inAVillageOf: "एका गावात",
    detectedEarly: "लवकर आढळले, दीर्घकालीन गुंतागुंत टाळली।",
    preventedEarly: "लवकर जीवनशैली हस्तक्षेपाद्वारे प्रतिबंधित।",
    identifiedImproving: "ओळखले गेले, माता आणि बाल आरोग्य सुधारले।",
    distribution: "वितरण",
    calculateImpact: "प्रभावाची गणना करा",
    city: "शहर",
    allIndia: "अखिल भारतीय",
    casesPreventable: "दरवर्षी प्रतिबंधात्मक प्रकरणे, लवकर AI स्क्रीनिंगसह",
    estSavings: "अंदाजे ₹{amount} L आरोग्य सेवा खर्च दरवर्षी वाचला",
    atRiskPopulation: "जोखिम असलेली लोकसंख्या",
    likelyUndiagnosed: "संभाव्यतः अनिदानित",
    detectableByAI: "AI द्वारे शोधण्यायोग्य",
    preventableCases: "प्रतिबंधात्मक प्रकरणे",
    methodology: "कार्यपद्धती",
    diabetesPrevalence: "मधुमेह प्रसार: 11.7% (ICMR-INDIAB अभ्यास)",
    hypertensionPrevalence: "उच्च रक्तदाब प्रसार: 28.6% (भारत उच्च रक्तदाब नियंत्रण पुढाकार)",
    anemiaPrevalence: "ॲनिमिया प्रसार: 53% (NFHS-5, महिला 15-49)",
    undiagnosedRate: "अनिदानित दर: ~50% (WHO भारत अहवाल 2023)",
    earlyDetectionAI: "AI स्क्रीनिंगद्वारे लवकर ओळख: अनिदानित प्रकरणांपैकी 35-45%",
    preventionRate: "प्रतिबंध दर: जीवनशैली हस्तक्षेपासह 60% (DPP अभ्यास)",
    shareWithDoctor: "डॉक्टरांशी शेअर करा",
    shareWithDoctorDesc: "आरोग्य सेवा व्यावसायिकाशी तुमचा नवीनतम भाकीत अहवाल शेअर करण्यासाठी QR कोड आणि सुरक्षित लिंक तयार करा।",
    generateShareLink: "QR कोड आणि शेअर लिंक तयार करा",
    nutriSubtitle: "भारतासाठी वैयक्तिकृत आहार नियोजन",
    nutriPlaceholder: "आहार, अन्न किंवा पोषणाबद्दल विचारा...",
    symptomsSubtitle: "AI-आधारित लक्षण विश्लेषण",
    symptomsPlaceholder: "कृपया तुमच्या लक्षणांचे वर्णन करा आणि मी मदत करण्याचा प्रयत्न करेन। तुम्ही व्हॉइस इनपुट देखील वापरू शकता",
    suggestDietAnemia: "ॲनिमियासाठी आहाराची शिफारस करा",
    lowSugarPlan: "कमी साखरेचा भारतीय जेवण प्लॅन",
    threeDayPlan: "3-दिवसीय निरोगी आहार नियोजन",
    feelDizzy: "मला चक्कर येत आहे",
    chestHurts: "माझ्या छातीत दुखत आहे",
    persistentCough: "मला सतत खोकला येत आहे",
    anemiaPrediction: "ॲनिमियाची भविष्यवाणी",
    diabetesPrediction: "मधुमेहाची भविष्यवाणी",
    hypertensionPrediction: "उच्च रक्तचापची भविष्यवाणी",
    tabularInput: "टॅबुलर इनपुट",
    imageAnalysis: "प्रतिमा विश्लेषण",
    uploadLabReport: "तुमच्या लॅब रिपोर्ट / रक्त चाचणीचा फोटो अपलोड करा।",
    uploadLabReportDesc: "तुमच्या लॅब रिपोर्ट / रक्त चाचणीचा फोटो अपलोड करा।",
    clickOrDragLabReport: "लॅब रिपोर्टची प्रतिमा येथे क्लिक करा किंवा ड्रॅग आणि ड्रॉप करा",
    supportsJpgPng: "JPG, PNG ला सपोर्ट करते (कमाल 5MB)",
    loadSampleReport: "नमुना अहवाल लोड करा",
    multiModalAnalysis: "मल्टी-मोडल: तळहात / कंजंक्टिवा प्रतिमा विश्लेषण",
    multiModalDesc: "AI-आधारित रंग विश्लेषणासाठी तुमच्या तळहाताचा, नखांचा किंवा खालच्या पापणीचा स्पष्ट फोटो अपलोड करा। सिस्टम RGB चॅनेल टक्केवारी काढते आणि हिमोग्लोबिन पातळीचा अंदाज लावते।",
    selectGender: "लिंग निवडा",
    clickOrDragPalm: "तळहाताचा फोटो येथे क्लिक करा किंवा ड्रॅग आणि ड्रॉप करा",
    loadSamplePalm: "नमुना तळहात लोड करा",
    analyseImage: "प्रतिमेचे विश्लेषण करा",
    quickFill: "त्वरित भरण्याचा पर्याय (डेटाबेस मधून एक यादृच्छिक नमुना निवडा)",
    predict: "भाकीत करा",
    processingReport: "अहवाल प्रक्रिया होत आहे...",
    age: "वय",
    sex: "लिंग",
    male: "पुरुष",
    female: "स्त्री",
    glucose: "ग्लुकोज",
    bloodPressure: "रक्तदाब",
    bmi: "बीएमआय",
    insulin: "इन्सुलिन",
    pregnancies: "गर्भधारणा",
    skinThickness: "त्वचेची जाडी",
    diabetesPedigree: "मधुमेह वंशावली कार्य",
    smoking: "धूम्रपान",
    alcohol: "अल्कोहोलचा हेतू",
    activity: "शारीरिक क्रियाकलाप",
    salt: "मिठाचे सेवन",
    chronic: "जुनाट परिस्थिती",
    familyHistory: "कौटुंबिक इतिहास",
    heartDisease: "मागील हृदयविकार",
    medication: "औषधांचा वापर",
    stress: "तणाव पातळी",
    sleep: "झोपेचे तास",
    systolic: "सिस्टोलिक बीपी",
    diastolic: "डायस्टोलिक बीपी",
    heartRate: "हृदय गती",
    cholesterol: "कोलेस्ट्रॉल",
    creatinine: "क्रिएटिनिन",
    dietType: "आहाराचा प्रकार",
    modelInsightsDashboard: "मॉडेल अंतर्दृष्टी डॅशबोर्ड",
    modelInsightsDesc: "सर्व एन्सेम्बल मॉडेल्ससाठी कार्यप्रदर्शन मेट्रिक्स, SHAP स्पष्टीकरण आणि जोखीम कल विश्लेषण।",
    liveAnalysis: "लाइव्ह विश्लेषण",
    accuracyComparison: "मॉडेल अचूकता तुलना",
    model: "मॉडेल",
    topFeatures: "शीर्ष वैशिष्ट्ये",
    riskTrendProjection: "6-महिन्यांचा जोखीम कल प्रक्षेपण",
    riskTrendDesc: "योग्य उपचार पालन आणि जीवनशैलीतील बदलांसह सिम्युलेटेड जोखीम कमी करणे।",
    ensembleArchitecture: "एन्सेम्बल आर्किटेक्चर",
    architecture: "आर्किटेक्चर",
    features: "वैशिष्ट्ये",
    trainingSamples: "प्रशिक्षण नमुने",
    finalAccuracy: "अंतिम अचूकता",
    projectedTrendsNote: "केवळ शैक्षणिक उद्देशांसाठी अंदाजित कल।",
    softVotingNote: "सर्व मॉडेल्स सॉफ्ट वोटिंग एन्सेम्बल (RandomForest + XGBoost + LightGBM) वापरतात",
    keyFeatures: "प्रमुख वैशिष्ट्ये",
    diseasePredictionTitle: "रोग भाकीत",
    diseasePredictionDesc: "मधुमेह, ॲनिमिया, उच्च रक्तदाबासाठी एन्सेम्बल ML (RF + XGBoost + LightGBM)",
    voiceInputTitle: "व्हॉइस इनपुट",
    voiceInputDesc: "तुमची लक्षणे किंवा आरोग्य डेटा बोला - इंग्रजी, हिंदी आणि मराठीमध्ये कार्य करते",
    multiModalAnemiaTitle: "मल्टी-मोडल ॲनिमिया",
    multiModalAnemiaDesc: "AI-आधारित रंग विश्लेषण + टॅब्युलर एन्सेम्बल फ्यूजनसाठी तळहाताचा फोटो अपलोड करा",
    shapExplainabilityTitle: "SHAP स्पष्टीकरण",
    shapExplainabilityDesc: "व्हिज्युअल SHAP बारसह प्रत्येक भाकीत का केले गेले ते नेमके पहा",
    personalizedPlansTitle: "वैयक्तिकृत योजना",
    personalizedPlansDesc: "Gemini AI तुमच्या भाषेत आहार, व्यायाम आणि जीवनशैली योजना तयार करते",
    pdfReportsTitle: "PDF अहवाल",
    pdfReportsDesc: "एका क्लिकवर व्यावसायिक क्लिनिकल अहवाल डाउनलोड करा",
    pancreasMonitoring: "स्वादुपिंड: मधुमेह जोखीम देखरेख",
    heartMonitoring: "हृदय: उच्च रक्तदाब देखरेख",
    bloodMonitoring: "रक्त: ॲनिमिया देखरेख",
    demoMode: "डेमो मोड - भारतीय रुग्ण डेटा ऑटो-फिल करा आणि भाकीत करा",
    futureRiskTimeline: "भविष्य जोखीम टाइमलाइन",
    shapExplainabilityPlots: "SHAP स्पष्टीकरण प्लॉट्स",
    shapDesc: "बीस्वर्म प्लॉट्स दर्शवतात की प्रत्येक वैशिष्ट्य वैयक्तिक भाकितांवर कसा परिणाम करते। लाल = उच्च वैशिष्ट्य मूल्य, निळा = कमी।",
    shapFeatureImpact: "SHAP वैशिष्ट्य प्रभाव",
    shapValueImpact: "SHAP मूल्य (मॉडेल आउटपुटवर प्रभाव)",
    shapMeanImportance: "SHAP सरासरी महत्त्व",
    meanFeatureImportance: "सरासरी वैशिष्ट्य महत्त्व",
    meanShapValueImpact: "सरासरी (|SHAP मूल्य|) (मॉडेल आउटपुट मॅग्निट्यूडवर सरासरी प्रभाव)",
    bpProduct: "बीपी उत्पादन",
    bmiAge: "बीएमआय वय",
    stressLevel: "तणाव पातळी",
    riskCombo: "जोखीम कॉम्बो",
    cholGlucose: "चोल ग्लुकोज",
    hb: "एचबी",
    greenPixel: "%हिरवा पिक्सेल",
    redPixel: "%लाल पिक्सेल",
    bluePixel: "%निळा पिक्सेल",
    featureValue: "वैशिष्ट्य मूल्य",
    high: "उच्च",
    low: "कमी",
  }
};
